### ISSUE TITLE
SESOI Error

### ISSUE THREAD

**Issue by oricon** [DejanDraschkow/mixedpower#3]
Hi, I'm getting an error about the length for SESOI even though I checked and the length for SESOI and my coefficients match. It isn't the warning mentioned in the FAQ, this is an error that stops the command from running. I am running mixedpower v. 0.1.0 installed from github with devtools in R 4.2.0

```
sesoi <- c(-0.83, .005, .042, .028, -.14, .016, .076, .008)
> length(sesoi)
[1] 8
> length(row.names(summary(power_fit_m1$full_model)$coefficients))
[1] 8

> power <- mixedpower(model = power_fit_m1$full_model, data = cleanChoicedata_prob,
+                         fixed_effects = c("cueValidity","prevRew", "rewCond"),
+                         simvar = "participant", steps = c(250,300,350,400,450,500),
+                         critical_value = 2, n_sim = 1000, SESOI = sesoi, databased = T)
Error in if (SESOI != F & length(SESOI) != length(row.names(summary(model)$coefficients))) { : 
  the condition has length > 1
```

Thanks for any guidance on this. I can run the power analysis without SESOI.

**Comment by anikokusztor** [comment]
I have encountered the same issue with the same set-up.

**Comment by jgeller112** [comment]
@DejanDraschkow  I just started getting this error on a new machine. It works on my older machine. Any fix or workaround?

Slight variation to this: 1. Why do I get this warning message when specifying a SESOI?
This warning message can be ignored and is removed in the newest update of the 	 	
mixedpower package. It is raised when mixedpower tries to determine if a SESOI is 	 	
specified and SESOI != FALSE.

Only it does not run

**Comment by lkumle** [comment]
Hi all, 

Thanks for bringing this issue to our attention! This error message seems to arise for R > 4.2.0. We have updated mixedpower accordingly. Updating/reinstalling mixedpower should solve the issue. We will also include this information in the FAQ.

**Comment by ThemisEfth** [comment]
Hello, 

Sorry to reopen this discussion. I wanted to mention I noticed this error when using the R2power function. I have re-installed the package but it still persists.
